<a href="https://colab.research.google.com/github/devamsheth21/Finite-Element-Analysis-codes/blob/main/FEA_CODE_SPRING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***GLOBAL STIFFNESS MATRIX***

In [ ]:
#final

import numpy
tn = int(input('Enter the total number of nodes : ')) #total nodes
te = int(input('Enter the total number of Elements : ')) #total elements
A=[]
K=[]
elstmat=[]
for i in range(te):
    stiffness= float(input('Enter the K of section of element '+str(i+1)+' in N/mm: '))
    A.append(stiffness)
for i in range(te):
    S=A[i]*numpy.array([[1,-1],[-1,1]])
    elstmat.append(S)
    print(" Stiffness matrix for element" ,i, "is : K",i,"= \n", elstmat[i])
c=[]
d=[]
e = numpy.zeros((tn,tn))
for i in range(te):  
    start = int(input('Enter the Start node of element '+str(i+1)+' : '))
    end = int(input('Enter the End node of element '+str(i+1)+' : '))
    if (start>end):
        c=start
        start=end
        end=c
    n=abs(start-end)
    stiffness=A[i]
    e[start-1][end-(n+1)]= e[start-1][end-(n+1)]+stiffness
    e[start-1][end-1]=e[start-1][end-1]-stiffness
    e[start+(n-1)][end-(n+1)]=e[start+(n-1)][end-(n+1)]-stiffness
    e[start+(n-1)][end-1]=e[start+(n-1)][end-1]+stiffness       
print(e)

Enter the total number of nodes : 3
Enter the total number of Elements : 2
Enter the K of section of element 1 in N/mm: 1
Enter the K of section of element 2 in N/mm: 1.4
 Stiffness matrix for element 0 is : K 0 = 
 [[ 1. -1.]
 [-1.  1.]]
 Stiffness matrix for element 1 is : K 1 = 
 [[ 1.4 -1.4]
 [-1.4  1.4]]
Enter the Start node of element 1 : 1
Enter the End node of element 1 : 3
Enter the Start node of element 2 : 3
Enter the End node of element 2 : 2
[[ 1.   0.  -1. ]
 [ 0.   1.4 -1.4]
 [-1.  -1.4  2.4]]


###  **FORCE CALCULATION** 


In [ ]:
#FORCE
displist = []
forcelist = []
for i in range(tn):
    a = str('u')+str(i+1)
    displist.append(a)
    # b = str('v')+str(i+1)
    # displist.append(b)
    c = str('fx')+str(i+1)
    forcelist.append(c)
    # d = str('fy')+str(i+1)
    # forcelist.append(d)

##print(displist)
##print(forcelist)
    
print('\n\n_______Support Specifications_____\n')

dispmat = numpy.ones((tn,1))
tsupn = int(input('Enter the total number of nodes having supports : ')) #total number of supported nodes
supcondition = ['P = pinned',
                'H = Horizonal restrained (vertical is free to move)',
                'V = Vertical restrained (Horizontal is free to move)']
   
for i in range(tsupn):
    supn = int(input('\nEnter the node number of suuport : ')) #supported node
    for a in supcondition:
        print(a)
    condition = str(input('\nEnter the condition of the support : '))
    if condition in['P', 'p']:
        dispmat[supn-1, 0] = 0
        # dispmat[supn*2-1, 0] = 0
    # elif condition in['H', 'h']:
    #     dispmat[supn-1, 0] = 0

    else:
        print('Please enter valid entries')
##print(dispmat)


print('\n______Loading_______\n')
forcemat = numpy.zeros((tn,1))
tlon = int(input('Enter the total number of loaded nodes : ')) #total number of loaded nodes

for i in range(tlon):
    lon = int(input('\nEnter the node number of Loading : ')) #Loaded node
    fx = float(input('Enter the Horizontal load at this node in N : '))
    # fy = float(input('Enter the Vertical load at this node in N : '))
    forcemat[lon-1, 0] = fx

##print(forcemat)    


###______Matrix Reduction______###


rcdlist = []
for i in range(tn):
    if dispmat[i,0] == 0:
        rcdlist.append(i)

rrgsm = numpy.delete(e, rcdlist, 0) #row reduction
crgsm = numpy.delete(rrgsm, rcdlist, 1) #column reduction
rgsm = crgsm #reduced global stiffness matrix
rforcemat = numpy.delete(forcemat, rcdlist, 0) #reduced force mat
rdispmat = numpy.delete(dispmat, rcdlist, 0) #reduced disp mat

###______Solving_______###

dispresult = numpy.matmul(numpy.linalg.inv(rgsm), rforcemat)
rin = 0
for i in range(tn):
    if dispmat[i,0] == 1:
        dispmat[i,0] = dispresult[rin,0]
        rin = rin+1
##print(dispmat)

forceresult = numpy.matmul(e, dispmat)
##print(forceresult)

print('\n\nGlobal Stiffness Matrix of the Truss\n')
print(e)
print('\n\nDisplacement matrix of nodes\n')
print(dispmat)
print('\n\nForce matrix of nodes\n')
print(forceresult)





_______Support Specifications_____

Enter the total number of nodes having supports : 1

Enter the node number of suuport : 1
P = pinned
H = Horizonal restrained (vertical is free to move)
V = Vertical restrained (Horizontal is free to move)

Enter the condition of the support : p

______Loading_______

Enter the total number of loaded nodes : 1

Enter the node number of Loading : 3
Enter the Horizontal load at this node in N : 800


Global Stiffness Matrix of the Truss

[[ 35. -15.   0. -20.]
 [-15.  30. -15.   0.]
 [  0. -15.  45. -30.]
 [-20.   0. -30.  50.]]


Displacement matrix of nodes

[[ 0.        ]
 [20.51282051]
 [41.02564103]
 [24.61538462]]


Force matrix of nodes

[[-800.]
 [   0.]
 [ 800.]
 [   0.]]
