<a href="https://colab.research.google.com/github/devamsheth21/Finite-Element-Analysis-codes/blob/main/FEA_TRUSS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import math
import numpy

numpy.set_printoptions(3, suppress=True)

t_n = int(input('Enter the total number of nodes : ')) #total nodes
te = int(input('Enter the total number of Elements : ')) #total elements
x_coord = [] #x co ordinate of nodes
y_coord = [] #y co ordinate of nodes
for i in range(t_n):
    x = float(input('Enter the x co-ordinate of node '+str(i+1)+' in mm : '))
    y = float(input('Enter the y co-ordinate of node '+str(i+1)+' in mm : '))
    x_coord.append(x)
    y_coord.append(y)

##print(x_coord)
##print(y_coord)
A=[]
E=[]
for i in range(te) :
    area = float(input('Enter the Area of cross section of element '+str(i+1)+' in mm2: '))
    ela = float(input('Enter the Modulous of Elasticity of element '+str(i+1)+' in N/mm2 : '))
    A.append(area)
    E.append(ela)
stratnodes = [] #start node of elements
endnodes = [] #end node of elements
lengthofel = [] #length of the element
el_con = [] #constant of the element
cosofel = [] #cos of element
sinofel = [] #sin of element

for i in range(te):  
    a = int(input('Enter the Start node of element '+str(i+1)+' : '))
    b = int(input('Enter the End node of element '+str(i+1)+' : '))
    x1 = float(x_coord[a-1])
    y1 = float(y_coord[a-1])
    x2 = float(x_coord[b-1])
    y2 = float(y_coord[b-1])
    l = math.sqrt((x2-x1)**2+(y2-y1)**2)
    con = A[i]*E[i]/l
    cos = (x2-x1)/l
    sin = (y2-y1)/l
    
    stratnodes.append(a)
    endnodes.append(b)
    lengthofel.append(l)
    el_con.append(con)
    cosofel.append(cos)
    sinofel.append(sin)
    
# print(stratnodes)
# print(endnodes)
print("\n",lengthofel, " lenghth of element")
print(el_con, " k =A*E/L of element ")
print(cosofel, " cos of elements")
print(sinofel, " sin of elements ")
sinofel = numpy.array(sinofel)
cosofel = numpy.array(cosofel)
print(sinofel*cosofel, " sin *cos or l*m")
print(sinofel*sinofel, " sin*sin or m*m")
print(cosofel*cosofel, " cos*cos or l*l")

Enter the total number of nodes : 4
Enter the total number of Elements : 3
Enter the x co-ordinate of node 1 in mm : 7800
Enter the y co-ordinate of node 1 in mm : 0
Enter the x co-ordinate of node 2 in mm : 0
Enter the y co-ordinate of node 2 in mm : 13510
Enter the x co-ordinate of node 3 in mm : 0
Enter the y co-ordinate of node 3 in mm : 0
Enter the x co-ordinate of node 4 in mm : 0
Enter the y co-ordinate of node 4 in mm : -4503.321
Enter the Area of cross section of element 1 in mm2: 680
Enter the Modulous of Elasticity of element 1 in N/mm2 : 280000
Enter the Area of cross section of element 2 in mm2: 680
Enter the Modulous of Elasticity of element 2 in N/mm2 : 280000
Enter the Area of cross section of element 3 in mm2: 680
Enter the Modulous of Elasticity of element 3 in N/mm2 : 280000
Enter the Start node of element 1 : 1
Enter the End node of element 1 : 2
Enter the Start node of element 2 : 1
Enter the End node of element 2 : 3
Enter the Start node of element 3 : 1
Enter the

In [ ]:
elstmat = [] #element stiffness matrix

for i in range(te):
    cc = float(cosofel[i])**2
    ss = float(sinofel[i])**2
    cs = float(cosofel[i])*float(sinofel[i])
    
    mat = el_con[i]*numpy.array([[cc, cs, -cc, -cs],
                      [cs, ss, -cs, -ss],
                      [-cc, -cs, cc, cs],
                      [-cs, -ss, cs, ss]])

    elstmat.append(mat)
    print(" Stiffness matrix for element" ,i, "is : K",i,"= \n", elstmat[i])


gstmatmap = []                          ## Global stiffness matrix mapping, gstmatmap will be the sqare matrix of t_n*
for i in range(te):                     ## do this for each elements
    m = stratnodes[i]*2                     ## taking the start node of element(i) and multiply by 2
    n = endnodes[i]*2                     ## taking the end node of element(i) and multiply by 2
    add = [m-1, m, n-1, n]              ## Address of columns and rows of gstmatmap for elemet(i)
                                            # if start_node is 1 and end node is 2 then add=[1,2,3,4]
                                            # if start_node is 1 and end node is 3 then add=[1,2,5,6]
    gmat = numpy.zeros((t_n*2, t_n*2))    ## global stiffness matrix loaded with zeros for element(i)
    elmat = elstmat[i]                  ## taking the element stiffness matrix of element(i)
    for j in range(4):                  
        for k in range(4):              
            a = add[j]-1                ## addressing row of GST matrix for element(i)
            b = add[k]-1                ## addressing column of GST matrix for element(i)
            gmat[a,b] = elmat[j,k]      ## updating the values in GST matrix with EST matrix of element(i)
    gstmatmap.append(gmat)              ## storing the resultant matrix in gstmatmap list
##    print(numpy.around(gmat, 3))

GSM = numpy.zeros((t_n*2, t_n*2))         ## creating an empyty GSM matrix
for mat in gstmatmap:
    GSM = GSM+mat                       ## adding all the matrix in the gstmatmap list
                                            # this will result in assembled stiffness matrix of the truss structure

print('\nGlobal Stiffness Matrix of the Truss\n')
print(numpy.around(GSM, 3))

 Stiffness matrix for element 0 is : K 0 = 
 [[ 3051.28  -5284.974 -3051.28   5284.974]
 [-5284.974  9153.846  5284.974 -9153.846]
 [-3051.28   5284.974  3051.28  -5284.974]
 [ 5284.974 -9153.846 -5284.974  9153.846]]
 Stiffness matrix for element 1 is : K 1 = 
 [[ 24410.256     -0.    -24410.256      0.   ]
 [    -0.         0.         0.        -0.   ]
 [-24410.256      0.     24410.256     -0.   ]
 [     0.        -0.        -0.         0.   ]]
 Stiffness matrix for element 2 is : K 2 = 
 [[ 15854.956   9153.841 -15854.956  -9153.841]
 [  9153.841   5284.959  -9153.841  -5284.959]
 [-15854.956  -9153.841  15854.956   9153.841]
 [ -9153.841  -5284.959   9153.841   5284.959]]

Global Stiffness Matrix of the Truss

[[ 43316.493   3868.867  -3051.28    5284.974 -24410.256      0.
  -15854.956  -9153.841]
 [  3868.867  14438.805   5284.974  -9153.846      0.         0.
   -9153.841  -5284.959]
 [ -3051.28    5284.974   3051.28   -5284.974      0.         0.
       0.         0.   ]
 [  5

FORCE CALCULATION


In [ ]:
displist = []
forcelist = []
for i in range(t_n):
    a = str('u')+str(i+1)
    displist.append(a)
    b = str('v')+str(i+1)
    displist.append(b)
    c = str('fx')+str(i+1)
    forcelist.append(c)
    d = str('fy')+str(i+1)
    forcelist.append(d)

##print(displist)
##print(forcelist)
    
print('\n\n________________Support Specifications______________\n')

dispmat = numpy.ones((t_n*2,1))
tsupn = int(input('Enter the total number of nodes having supports : ')) #total number of supported nodes
supcondition = ['P = pinned',
                'H = Horizonal restrained (vertical is free to move)',
                'V = Vertical restrained (Horizontal is free to move)']
   
for i in range(tsupn):
    supn = int(input('\nEnter the node number of suuport : ')) #supported node
    for a in supcondition:
        print(a)
    condition = str(input('\nEnter the condition of the support : '))
    if condition in['P', 'p']:
        dispmat[supn*2-2, 0] = 0
        dispmat[supn*2-1, 0] = 0
    elif condition in['H', 'h']:
        dispmat[supn*2-2, 0] = 0
    elif condition in['V', 'v']:
        dispmat[supn*2-1, 0] = 0
    else:
        print('Please enter valid entries')
##print(dispmat)


print('\n_________________Loading____________________\n')
forcemat = numpy.zeros((t_n*2,1))
tlon = int(input('Enter the total number of loaded nodes : ')) #total number of loaded nodes

for i in range(tlon):
    lon = int(input('\nEnter the node number of Loading : ')) #Loaded node
    fx = float(input('Enter the Horizontal load at this node in N : '))
    fy = float(input('Enter the Vertical load at this node in N : '))
    forcemat[lon*2-2, 0] = fx
    forcemat[lon*2-1, 0] = fy

##print(forcemat)    


###_________________Matrix Reduction_________________###


rcdlist = []
for i in range(t_n*2):
    if dispmat[i,0] == 0:
        rcdlist.append(i)

rrgsm = numpy.delete(GSM, rcdlist, 0) #row reduction
crgsm = numpy.delete(rrgsm, rcdlist, 1) #column reduction
rgsm = crgsm #reduced global stiffness matrix
rforcemat = numpy.delete(forcemat, rcdlist, 0) #reduced force mat
rdispmat = numpy.delete(dispmat, rcdlist, 0) #reduced disp mat

###_______________Solving____________________###

dispresult = numpy.matmul(numpy.linalg.inv(rgsm), rforcemat)
rin = 0
for i in range(t_n*2):
    if dispmat[i,0] == 1:
        dispmat[i,0] = dispresult[rin,0]
        rin = rin+1
##print(dispmat)

forceresult = numpy.matmul(GSM, dispmat)
##print(forceresult)

print('\n\nGlobal Stiffness Matrix of the Truss\n')
print(GSM)
print('\n\nDisplacement matrix of nodes\n')
print(dispmat)
print('\n\nForce matrix of nodes\n')
print(forceresult)

##____________________new co ordinates of nodes____________####

newx_coord = []
newy_coord = []
count = 0
for i in range(t_n):
    k = x_coord[i]+dispmat[count,0]
    newx_coord.append(k)
    count = count+1
    l = y_coord[i]+dispmat[count,0]
    newy_coord.append(l)
    count = count+1

###____________________new length of memebers______________####
    
newlengthofel = []
for i in range(te):
    a, b = stratnodes[i], endnodes[i]
    x1 = float(newx_coord[a-1])
    y1 = float(newy_coord[a-1])
    x2 = float(newx_coord[b-1])
    y2 = float(newy_coord[b-1])
    l = math.sqrt((x2-x1)**2+(y2-y1)**2)
    newlengthofel.append(l)

##print(newlengthofel)
##print(lengthofel)

###______________strain in elements_______________________###
    
numpy.set_printoptions(3, suppress=False)

elstrain = numpy.zeros((te,1))
for i in range(te):
    elstrain[i,0] = (newlengthofel[i]-lengthofel[i])/(lengthofel[i])
print('\n***Positive is Tensile\nNegetive is Compressive***\n')

print('\n\nStrain in the elements')
print(elstrain)
# numpy.set_printoptions(3, suppress=True)

###__________________stress in elements______________________###

elstress = numpy.zeros((te,1))
for i in range(te):
    elstress[i,0] = E[i] * elstrain[i,0]
    
print('\n\nStress in the elements')
print(elstress)

###_________________Member forces____________________#########

eforce = numpy.zeros((te,1))
for i in range(te):
    eforce[i,0] = A[i] * elstress[i,0]

print('\n\nForce in the element')
print(eforce)



________________Support Specifications______________

Enter the total number of nodes having supports : 3

Enter the node number of suuport : 2
P = pinned
H = Horizonal restrained (vertical is free to move)
V = Vertical restrained (Horizontal is free to move)

Enter the condition of the support : p

Enter the node number of suuport : 3
P = pinned
H = Horizonal restrained (vertical is free to move)
V = Vertical restrained (Horizontal is free to move)

Enter the condition of the support : p

Enter the node number of suuport : 4
P = pinned
H = Horizonal restrained (vertical is free to move)
V = Vertical restrained (Horizontal is free to move)

Enter the condition of the support : p

_________________Loading____________________

Enter the total number of loaded nodes : 1

Enter the node number of Loading : 1
Enter the Horizontal load at this node in N : 33000
Enter the Vertical load at this node in N : 19000


Global Stiffness Matrix of the Truss

[[ 43316.493   3868.867  -3051.28    528